export interface Customer {
    id: number,
    name: string,
    tanggal_lahir: Date | null,
    address: string,
    handphone: string,
    email: string | null,
    profesi: string | null,
    status_perkawinan: string | null,
    tanda_pengenal: string, // nik
    image_tanda_pengenal: string,
    image_selfie: string,
    created_at: Date | null,
    deleted_at: Date | null,
    NoCustomer: string,
    IDCustomerStamps: string | null
}

export const dataCustomer: Customer[] = [
    {
        id: 1,
        name: "Bunga Lavender",
        tanggal_lahir: new Date(2004, 6, 12),
        handphone: "08123456701",
        address: "Jl. Menuju Kesuksesan",
        email: "bungalavender@gmail.com",
        profesi: "Florist",
        status_perkawinan: "Lajang",
        image_tanda_pengenal: "/image/bg-login.jpg",
        image_selfie: "/image/bg-login.jpg",
        tanda_pengenal: "3171234567890001",
        created_at: null,
        deleted_at: null,
        NoCustomer: "CUST-0001",
        IDCustomerStamps: null
    },
    {
        id: 2,
        name: "Bunga Lily",
        tanggal_lahir: new Date(2000, 7, 5),
        address: "Jl. Jalan",
        handphone: "08123456702",
        email: "bungalily@gmail.com",
        profesi: "Karyawan",
        status_perkawinan: "Menikah",
        image_tanda_pengenal: "/image/bg-login.jpg",
        image_selfie: "/image/bg-login.jpg",
        tanda_pengenal: "3171234567890002",
        created_at: null,
        deleted_at: null,
        NoCustomer: "CUST-0002",
        IDCustomerStamps: null
    },
    {
        id: 3,
        name: "Bunga Mawar",
        tanggal_lahir: new Date(2004, 5, 25),
        address: "Jl. Jalan",
        handphone: "08123456703",
        email: "bungamawar@gmail.com",
        profesi: "Ibu Rumah Tangga",
        status_perkawinan: "Menikah",
        image_tanda_pengenal: "/image/bg-login.jpg",
        image_selfie: "/image/bg-login.jpg",
        tanda_pengenal: "3171234567890003",
        created_at: null,
        deleted_at: null,
        NoCustomer: "CUST-0003",
        IDCustomerStamps: null
    },
    {
        id: 4,
        name: "Bunga Matahari",
        tanggal_lahir: new Date(2003, 2, 12),
        address: "Jl. Jalan",
        handphone: "08123456704",
        email: "bungamatahari@gmail.com",
        profesi: "Pegawai Negeri",
        status_perkawinan: "Lajang",
        image_tanda_pengenal: "/image/bg-login.jpg",
        image_selfie: "/image/bg-login.jpg",
        tanda_pengenal: "3171234567890004",
        created_at: null,
        deleted_at: null,
        NoCustomer: "CUST-0004",
        IDCustomerStamps: null
    },
    {
        id: 5,
        name: "Bunga Sakura",
        tanggal_lahir: new Date(2002, 9, 12),
        address: "Jl. Jalan",
        handphone: "08123",
        email: "bungabunga@gmail.com",
        profesi: "Petani",
        status_perkawinan: "Lajang",
        image_tanda_pengenal: "/image/bg-login.jpg",
        image_selfie: "/image/bg-login.jpg",
        tanda_pengenal: "3171234567890005",
        created_at: null,
        deleted_at: null,
        NoCustomer: "",
        IDCustomerStamps: null
    },
    {
        id: 6,
        name: "Agustin",
        tanggal_lahir: new Date(1998, 4, 10),
        address: "Jl. Test Gadai Ulang",
        handphone: "081234567806",
        email: "gadaiulangbaru@test.com",
        profesi: "Karyawan",
        status_perkawinan: "Lajang",
        image_tanda_pengenal: "/image/bg-login.jpg",
        image_selfie: "/image/bg-login.jpg",
        tanda_pengenal: "",
        created_at: null,
        deleted_at: null,
        NoCustomer: "CUST-006",
        IDCustomerStamps: null,
    },
    {
        id: 7,
        name: "Testing Payment Akan Lunas",
        tanggal_lahir: new Date(1995, 8, 20),
        address: "Jl. Test Akan Lunas",
        handphone: "081234567807",
        email: "akanlunas@test.com",
        profesi: "Wiraswasta",
        status_perkawinan: "Menikah",
        image_tanda_pengenal: "/image/bg-login.jpg",
        image_selfie: "/image/bg-login.jpg",
        tanda_pengenal: "",
        created_at: null,
        deleted_at: null,
        NoCustomer: "CUST-007",
        IDCustomerStamps: null,
    },
    {
        id: 8,
        name: "Test Tanpa Status",
        tanggal_lahir: new Date(1999, 1, 15),
        address: "Jl. Test Tanpa Status",
        handphone: "081234567808",
        email: null,
        profesi: "Pedagang",
        status_perkawinan: "Lajang",
        image_tanda_pengenal: "/image/bg-login.jpg",
        image_selfie: "/image/bg-login.jpg",
        tanda_pengenal: "",
        created_at: null,
        deleted_at: null,
        NoCustomer: "CUST-008",
        IDCustomerStamps: null,
    },
];