export interface Customer{
    id: number,
    name: string,
    tanggal_lahir: Date | null,
    address: string,
    handphone: string,
    email: string | null,
    profesi: string | null,
    status_perkawinan: string | null,
    tanda_pengenal: string, // nik
    image_tanda_pengenal: string,
    image_selfie: string,
    created_at: Date | null,
    deleted_at: Date | null,
    NoCustomer: string,
    IDCustomerStamps: string | null
}

export const dataCustomer: Customer[] = [
    {
        id: 1,
        name: "Bunga Lavender",
        tanggal_lahir: new Date(2004, 6, 12),
        handphone: "0",
        address: "Jl. Menuju Kesuksesan",
        email: "bungalavender@gmail.com",
        profesi: "Florist",
        status_perkawinan: "Lajang",
        image_tanda_pengenal: "/image/bg-login.jpg",
        image_selfie: "/image/bg-login.jpg",
        tanda_pengenal: "",
        created_at: null,
        deleted_at: null,
        NoCustomer: "",
        IDCustomerStamps: null
    },

    {
        id: 2,
        name: "Bunga Lily",
        tanggal_lahir: new Date(2000, 7, 5),
        address: "Jl. Jalan",
        handphone: "08123",
        email: "bungalily@gmail.com",
        profesi: "Karyawan",
        status_perkawinan: "Menikah",
        image_tanda_pengenal: "/image/bg-login.jpg",
        image_selfie: "/image/bg-login.jpg",
        tanda_pengenal: "",
        created_at: null,
        deleted_at: null,
        NoCustomer: "",
        IDCustomerStamps: null
    },
    {
        id: 3,
        name: "Bunga Mawar",
        tanggal_lahir: new Date(2004, 5, 25),
        address: "Jl. Jalan",
        handphone: "08123",
        email: "bungamawar@gmail.com",
        profesi: "Ibu Rumah Tangga",
        status_perkawinan: "Menikah",
        image_tanda_pengenal: "/image/bg-login.jpg",
        image_selfie: "/image/bg-login.jpg",
        tanda_pengenal: "",
        created_at: null,
        deleted_at: null,
        NoCustomer: "",
        IDCustomerStamps: null
    },
    {
        id: 4,
        name: "Bunga Matahari",
        tanggal_lahir: new Date(2003, 2, 12),
        address: "Jl. Jalan",
        handphone: "08123",
        email: "bungamatahari@gmail.com",
        profesi: "Pegawai Negeri",
        status_perkawinan: "Lajang",
        image_tanda_pengenal: "/image/bg-login.jpg",
        image_selfie: "/image/bg-login.jpg",
        tanda_pengenal: "",
        created_at: null,
        deleted_at: null,
        NoCustomer: "",
        IDCustomerStamps: null
    },
    {
        id: 5,
        name: "Bunga bungaan",
        tanggal_lahir: new Date(2002, 9, 12),
        address: "Jl. Jalan",
        handphone: "08123",
        email: "bungabunga@gmail.com",
        profesi: "Petani",
        status_perkawinan: "Lajang",
        image_tanda_pengenal: "/image/bg-login.jpg",
        image_selfie: "/image/bg-login.jpg",
        tanda_pengenal: "",
        created_at: null,
        deleted_at: null,
        NoCustomer: "",
        IDCustomerStamps: null
    }
];