import { Pawn } from "./data-pawn";
import { dataCustomer } from "./data-customer";

const emptyPawnFields = {
   oldApplication: "-",
   brand: "J2C",
   paymentMethod: "Transfer",
   disbursementType: "Transfer",
   storeId: "STORE-C",
   usersId: "JR-C",
   customerData: null,
   newPawnId: null,
   isNewJ2c: false,
   isRestock: false,
   isTakeOver: false,
   isGadaiResell: false,
   totalAppraisalPrice: 0,
   totalMaximumLoan: 0,
   disburseNominal: 0,
   interestPercentage: 0,
   interestNominal: 0,
   repaymentNominal: 0,
   interestRepaymentPercentage: null,
   interestRepaymentNominal: null,
   penaltyNominal: 0,
   storageInsuranceFeeNominal: 0,
   persentaseBiayaPerawatan: 0,
   goldRate: null,
   dueDate: null,
   lastSaleDate: null,
   topupDate: null,
   pawnDoneDate: null,
   pawnDoneBy: null,
   draftName: null,
   customerCurrentId: null,
   customerSgkId: null,
   requestDiscountId: null,
   document: null,
   approveNote: null,
   rejectedAt: null,
   rejectedBy: null,
   completedDocumentAt: null,
   completedDocumentBy: null,
   reviewedFinanceAt: null,
   reviewedFinanceBy: null,
   disbursedBy: null,
   disbursedAt: null,
   resellAt: null,
   resellBy: null,
   reason: null,
   updatedStatusAt: null,
   bankBranch: "-",
   applicationFormPhoto: null,
   pawnFormPhoto: null,
   sbgFormPhoto: null,
   suratKuasaPhoto: null,
   sealFormPhoto: null,
   sealedProductPhoto: null,
   invoice: null,
   suratsegel: null,
   irisReferenceNumber: null,
   jsonRequestPaid: null,
   jsonResponsePaid: null,
   nominalPelunasan: null,
   buktiTransferPelunasan: null,
   generateCode: null,
   noReferensi: null,
   referenceById: null,
   responseStatus: null,
   responseCmkapi: null,
   updatedAt: null,
   deletedAt: null,
   stampsCustomerId: null,
} satisfies Partial<Pawn>;

const generateDraftData = (appNumber: string, date: string, customerId: number, bankId: number) => {
    return {
        pawnItems: [
            {
                id: Math.floor(Math.random() * 10000),
                pawn_id: 4,
                pawn_item_code: "ITEM-260901-0001",
                pawn_item_type_id: 9,
                item_name: "Cincin Berlian Mewah",
                status: "stored",
                plu: "DJ001",
                weight: 5.5,
                weight_current: 5.5,
                carat: "75",
                carat_current: "75",
                photo: "/image/jewelry.jpg",
                quantity: 1,
                condition: "Excellent",
                appraisal: 9835366,
                max_loan_price: 8851829,
                remark: "Barang masih mulus",
                itemType: { id: 9, type: "dj", text: "Diamond Jewelry", status: 1 }
            }
        ],
        loanDetails: {
            applicationNumber: appNumber,
            tanggalTransaksi: new Date(date).toISOString().split('T')[0],
            tenor: "1",
            maksNilaiPinjaman: 8851829,
            nilaiPinjaman: 8500000,
            setMaksimalPinjaman: false,
            persentaseBiayaPerawatan: 0.75,
            bankId: bankId.toString(),
            cabang: "Sudirman",
            nomorRekening: bankId === 1 ? "0011223344" : "0099887766",
            namaPemilikRekening: bankId === 1 ? "BCA Simulator A" : "Bank Simulator A",
            tanggalJatuhTempo: new Date(new Date(date).getTime() + 15 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
            biayaAdmin: 35000,
            biayaPerawatan: 63750,
            totalNilaiPinjaman: 8401250,
            calculatedNilaiPinjaman: 8500000,
            catatan: "Catatan simulasi peminjaman",
            isCalculated: true,
            isRekeningChecked: true,
        },
        customerData: dataCustomer.find(c => c.id === customerId) || null
    };
};

export const pawnData: Pawn[] = [
   {
      ...emptyPawnFields,
      id: 1,
      type: "J2C",
      applicationNumber: "J2CE432608310001",
      pawnNumber: "PWN-260901-0001",
      dibuatOleh: "JR CMK",
      status: "created",
      customerId: 1,
      barangCodes: ["ITEM-260901-0001"],
      totalAppraisalPrice: 9835366,
      totalMaximumLoan: 8851829,
      nilaiPinjaman: 8500000,
      disburseNominal: 0,
      idPawnTenor: "1",
      tenor: 15,
      biayaAdmin: 35000,
      storageInsuranceFeePercentage: 0.06,
      persentaseBiayaPerawatan: 0.0075,
      tanggalTransaksi: new Date("2023-03-05T00:00:00"),
      statusNotification: null,
      remark: null,
      appraisal: null,
      bankId: 1,
      metodePencairan: "Transfer",
      nomorRekening: "0011223344",
      namaPemilikRekening: "BCA Simulator A",
      createdAt: new Date("2023-03-05T00:00:00"),
      createdBy: "JR CMK C",
      approvedAt: null,
      approvedBy: null,
      draftData: generateDraftData("J2CE432608310001", "2023-03-05T00:00:00", 1, 1)
   },
   {
      ...emptyPawnFields,
      id: 2,
      type: "J2C",
      applicationNumber: "J2CE432608310002",
      pawnNumber: "PWN-260901-0002",
      dibuatOleh: "JR CMK",
      status: "waiting_approval",
      customerId: 2,
      barangCodes: ["ITEM-260901-0001"],
      totalAppraisalPrice: 9835366,
      totalMaximumLoan: 8851829,
      nilaiPinjaman: 8500000,
      disburseNominal: 0,
      idPawnTenor: "1",
      tenor: 15,
      biayaAdmin: 35000,
      storageInsuranceFeePercentage: 0.06,
      persentaseBiayaPerawatan: 0.0075,
      statusNotification: null,
      tanggalTransaksi: new Date("2026-09-10T00:00:00"),
      remark: null,
      appraisal: null,
      bankId: 2,
      metodePencairan: "Transfer",
      nomorRekening: "0099887766",
      namaPemilikRekening: "Bank Simulator A",
      createdAt: new Date("2026-09-09T00:00:00"),
      createdBy: "JR CMK A",
      approvedAt: null,
      approvedBy: null,
      draftData: generateDraftData("J2CE432608310002", "2026-09-10T00:00:00", 2, 2)
   },
   {
      ...emptyPawnFields,
      id: 3,
      type: "J2C",
      applicationNumber: "J2CE432608310003",
      pawnNumber: "PWN-260901-0003",
      dibuatOleh: "JR CMK",
      status: "done",
      customerId: 3,
      barangCodes: ["ITEM-260901-0001"],
      totalAppraisalPrice: 9835366,
      totalMaximumLoan: 8851829,
      nilaiPinjaman: 8500000,
      disburseNominal: 8401250,
      idPawnTenor: "1",
      tenor: 15,
      biayaAdmin: 35000,
      storageInsuranceFeePercentage: 0.06,
      persentaseBiayaPerawatan: 0.0075,
      statusNotification: null,
      tanggalTransaksi: new Date("2026-01-08T00:00:00"),
      remark: null,
      appraisal: null,
      bankId: 1,
      metodePencairan: "Transfer",
      nomorRekening: "0011223344",
      namaPemilikRekening: "BCA Simulator A",
      createdAt: new Date("2026-01-08T00:00:00"),
      createdBy: "JR Transaction C",
      approvedAt: new Date("2026-01-08T10:30:00"),
      approvedBy: "Store Manager C",
      draftData: generateDraftData("J2CE432608310003", "2026-01-08T00:00:00", 3, 1)
   },
   {
      ...emptyPawnFields,
      id: 4,
      type: "J2C",
      applicationNumber: "J2CE432608310004",
      pawnNumber: "PWN-260901-0004",
      dibuatOleh: "JR CMK",
      status: "disbursed",
      customerId: 4,
      barangCodes: ["ITEM-260901-0001"],
      totalAppraisalPrice: 5726000,
      totalMaximumLoan: 8851829,
      nilaiPinjaman: 8500000,
      disburseNominal: 8401250,
      idPawnTenor: "1",
      tenor: 15,
      biayaAdmin: 35000,
      storageInsuranceFeePercentage: 0.06,
      persentaseBiayaPerawatan: 0.0075,
      statusNotification: "akan_lunas",
      tanggalTransaksi: new Date("2023-03-04T00:00:00"),
      remark: "Condition: Excellent",
      appraisal: 5726000,
      bankId: 2,
      metodePencairan: "Transfer",
      nomorRekening: "0011223344",
      namaPemilikRekening: "BCA Simulator A",
      createdAt: new Date("2023-03-03T00:00:00"),
      createdBy: "JR Transaction C",
      approvedAt: new Date("2023-03-05T00:00:00"),
      approvedBy: "Store Manager C",
      invoice: "/image/bg-login.jpg",
      suratsegel: "/image/bg-login.jpg",
      disbursedBy: "Finance C",
      disbursedAt: new Date("2023-03-05T11:00:00"),
      draftData: generateDraftData("J2CE432608310004", "2023-03-04T00:00:00", 4, 2)
   },
];
