export const item_type = [
  { 
    id:8, 
    type: "refinancing_cmk_dj_editable", 
    text: "CMK Diamond Jewelry",
    max_loan_excellent: 90.00,
    max_loan_good: 90.00,
    max_loan_fair: 90.00,
    storage_insurance_fee: 0.75,
    admin_fee: 0,
    interest_rate: 6,
    status: 1,
  },
  { 
    id:9, 
    type: "refinancing_cmk_pg_editable", 
    text: "CMK Plain Gold",
    max_loan_excellent: 90.00,
    max_loan_good: 90.00,
    max_loan_fair: 90.00,
    storage_insurance_fee: 0.75,
    admin_fee: 0,
    interest_rate: 6,
    status: 1,
  },
  { 
    id:13, 
    type: "cmk_manual_dj", 
    text: "CMK Diamond Jewelry (Manual Input)",
    max_loan_excellent: 90.00,
    max_loan_good: 90.00,
    max_loan_fair: 90.00,
    storage_insurance_fee: 0.75,
    admin_fee: 1,
    interest_rate: 1,
    status: 1,
  },
  { 
    id:14, 
    type: "cmk_manual_pg", 
    text: "CMK Plain Gold (Manual Input)",
    max_loan_excellent: 90.00,
    max_loan_good: 90.00,
    max_loan_fair: 90.00,
    storage_insurance_fee: 0.75,
    admin_fee: 1,
    interest_rate: 1,
    status: 1,
  },
] as const;